[Icon Theme]
Name=Wonderbrushed 0.4.1
Comment=Hand-drawn watercolor icons by Bhavneeth
Inherits=breeze-dark,hicolor
Example=folder

DisplayDepth=32
FollowsColorScheme=true

# All active directories declared in lowercase
Directories=apps,places,categories,mimetypes,status,devices

[apps]
Size=128
Context=Applications
Type=Scalable
MinSize=16
MaxSize=512

[places]
Size=128
Context=Places
Type=Scalable
MinSize=16
MaxSize=512

[categories]
Size=128
Context=Categories
Type=Scalable
MinSize=16
MaxSize=512

[mimetypes]
Size=128
Context=Mimetypes
Type=Scalable
MinSize=16
MaxSize=512

[status]
Size=22
Context=Status
Type=Scalable
MinSize=16
MaxSize=512

[devices]
Size=22
Context=Devices
Type=Scalable
MinSize=16
MaxSize=512
